theme: jekyll-theme-minimal
title: Portfolio | Aleksandra Nowak
description: Portfolio prac Aleksandry Nowak - studentki pierwszego roku architektury na Politechnice Łódzkiej.
logo: ./images/logo.JPG
